# Generated by Django 4.1.4 on 2023-12-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Averages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=255)),
                ("pts", models.FloatField()),
                ("reb", models.FloatField()),
                ("ast", models.FloatField()),
                ("stl", models.FloatField()),
                ("blk", models.FloatField()),
                ("tov", models.FloatField()),
            ],
        ),
    ]
